# Generated by Django 5.2.7 on 2026-01-06 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0012_alter_topic_order_alter_topic_topic_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_minutes', models.IntegerField(default=60)),
                ('pass_percentage', models.IntegerField(default=50)),
                ('total_marks', models.IntegerField(default=100)),
                ('topic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='curriculum.topic')),
            ],
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_type', models.CharField(choices=[('MCQ_SINGLE', 'Single Choice'), ('MCQ_MULTI', 'Multiple Choice'), ('CODE', 'Coding Challenge')], max_length=20)),
                ('text', models.TextField()),
                ('marks', models.IntegerField(default=5)),
                ('option_1', models.CharField(blank=True, max_length=255, null=True)),
                ('option_2', models.CharField(blank=True, max_length=255, null=True)),
                ('option_3', models.CharField(blank=True, max_length=255, null=True)),
                ('option_4', models.CharField(blank=True, max_length=255, null=True)),
                ('option_5', models.CharField(blank=True, max_length=255, null=True)),
                ('correct_options', models.CharField(blank=True, help_text="For Multi, separate with comma e.g. '1,3'", max_length=10, null=True)),
                ('starter_code', models.TextField(blank=True, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.exam')),
            ],
        ),
        migrations.CreateModel(
            name='ExamTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField()),
                ('expected_output', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='assessments.examquestion')),
            ],
        ),
        migrations.CreateModel(
            name='StudentExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.FloatField(default=0.0)),
                ('passed', models.BooleanField(default=False)),
                ('warnings_triggered', models.IntegerField(default=0)),
                ('is_auto_submitted', models.BooleanField(default=False)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.exam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
