# Generated by Django 5.2.7 on 2026-01-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexamattempt',
            name='response_data',
            field=models.JSONField(blank=True, default=dict, help_text='Stores user answers {question_id: answer}'),
        ),
    ]
