# Generated by Django 5.2.7 on 2026-01-28 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_studentexamattempt_response_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='examquestion',
            name='exam',
        ),
        migrations.AddField(
            model_name='studentexamattempt',
            name='section_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentexamattempt',
            name='response_data',
            field=models.JSONField(blank=True, default=dict, help_text='Stores structured user answers'),
        ),
        migrations.CreateModel(
            name='ExamSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=1)),
                ('duration_minutes', models.IntegerField(help_text='Time allocated for this specific section')),
                ('description', models.TextField(blank=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='assessments.exam')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='examquestion',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.examsection'),
        ),
        migrations.AddField(
            model_name='studentexamattempt',
            name='current_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessments.examsection'),
        ),
    ]
