# Generated by Django 5.2.7 on 2026-01-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_remove_exam_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestion',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image if the question requires one (e.g. Geometry figures)', null=True, upload_to='exam_images/'),
        ),
    ]
