# Generated by Django 5.2.7 on 2026-01-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_examquestion_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examquestion',
            name='image',
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='text',
            field=models.TextField(blank=True, help_text='Question text (Optional if using an image)', null=True),
        ),
    ]
