# Generated by Django 5.2.7 on 2026-02-24 18:04

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0008_publicexamlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examquestion',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='exam_images/'),
        ),
    ]
