# Generated by Django 5.2.7 on 2026-02-24 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0009_alter_examquestion_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexamattempt',
            name='public_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='assessments.publicexamlink'),
        ),
    ]
