# Generated by Django 5.2.7 on 2026-03-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0011_examtestcase_is_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examtestcase',
            name='expected_output',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examtestcase',
            name='input_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
