# Generated by Django 5.2.7 on 2026-03-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0012_alter_examtestcase_expected_output_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='max_attempts',
            field=models.IntegerField(default=2, help_text='Maximum attempts allowed for this exam'),
        ),
    ]
