# Generated by Django 5.2.7 on 2026-03-28 15:08

from django.db import migrations


def reset_attempt_counters(apps, schema_editor):
    ExamAttemptCounter = apps.get_model('assessments', 'ExamAttemptCounter')
    ExamAttemptCounter.objects.all().update(attempt_count=0)


def noop_reverse(apps, schema_editor):
    # Baseline migration; no reverse action required.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0014_examattemptresetlog_examattemptcounter'),
    ]

    operations = [
        migrations.RunPython(reset_attempt_counters, noop_reverse),
    ]
