# Generated by Django 5.2.7 on 2026-03-28 15:13

from django.db import migrations


def initialize_all_counters(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Exam = apps.get_model('assessments', 'Exam')
    ExamAttemptCounter = apps.get_model('assessments', 'ExamAttemptCounter')

    user_ids = list(User.objects.values_list('id', flat=True))
    exam_ids = list(Exam.objects.values_list('id', flat=True))

    if not user_ids or not exam_ids:
        ExamAttemptCounter.objects.all().update(attempt_count=0)
        return

    existing_pairs = set(
        ExamAttemptCounter.objects.values_list('user_id', 'exam_id')
    )

    to_create = []
    for user_id in user_ids:
        for exam_id in exam_ids:
            if (user_id, exam_id) not in existing_pairs:
                to_create.append(
                    ExamAttemptCounter(user_id=user_id, exam_id=exam_id, attempt_count=0)
                )

    if to_create:
        ExamAttemptCounter.objects.bulk_create(to_create, batch_size=2000)

    # Baseline everyone to start from 0 now, as requested.
    ExamAttemptCounter.objects.all().update(attempt_count=0)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0015_reset_existing_attempt_counters_to_zero'),
    ]

    operations = [
        migrations.RunPython(initialize_all_counters, noop_reverse),
    ]
