# Generated by Django 4.2.14 on 2026-04-28 17:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assessments", "0012_attempt_grading_status"),
        ("assessments", "0016_initialize_all_user_exam_attempt_counters"),
    ]

    operations = []
