# Generated by Django 5.2.7 on 2026-02-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='roll_number',
            field=models.CharField(blank=True, help_text='University Roll Number', max_length=50, null=True),
        ),
    ]
