# Generated by Django 5.2.7 on 2026-03-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_roll_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='force_password_change',
            field=models.BooleanField(default=False, help_text='If true, forces user to reset password on next login.'),
        ),
    ]
