# Generated by Django 4.2.14 on 2026-05-13 11:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_profile_force_password_change"),
        ("core", "0016_executionjob"),
    ]

    operations = []
