# Generated by Django 4.2.14 on 2026-05-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_merge_20260513_1700"),
    ]

    operations = [
        migrations.AlterField(
            model_name="executionjob",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
