# Generated by Django 5.2.7 on 2025-12-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_alter_dailyquestion_correct_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyquestion',
            name='starter_code',
            field=models.TextField(blank=True, help_text='Pre-filled code for the editor', null=True),
        ),
    ]
