# Generated by Django 5.2.7 on 2025-12-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_question_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True, help_text='Short summary for the course card'),
        ),
        migrations.AddField(
            model_name='subject',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='If set, shows original price with strikethrough', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subject',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
