# Generated by Django 5.2.7 on 2025-12-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='duration',
            field=models.CharField(blank=True, help_text='Estimated time to complete', max_length=50),
        ),
        migrations.AddField(
            model_name='topic',
            name='topic_type',
            field=models.CharField(choices=[('text', 'Text Article'), ('video', 'Video Lesson'), ('quiz', 'Quiz')], default='text', max_length=10),
        ),
        migrations.AddField(
            model_name='topic',
            name='video_id',
            field=models.CharField(blank=True, help_text='YouTube Video ID (e.g., dQw4w9WgXcQ)', max_length=20),
        ),
        migrations.AlterField(
            model_name='topic',
            name='content',
            field=models.TextField(blank=True, help_text='Main content for text lessons'),
        ),
    ]
