# Generated by Django 5.2.7 on 2026-01-06 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0011_alter_job_options_alter_jobapplication_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='order',
            field=models.FloatField(help_text='Use decimals (e.g., 1.5) to insert between topics'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_type',
            field=models.CharField(choices=[('text', 'Text Article'), ('video', 'Video Lesson'), ('quiz', 'Quiz'), ('exam', 'Mock Exam')], default='text', max_length=10),
        ),
    ]
