# Generated by Django 5.2.7 on 2026-02-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0012_alter_topic_order_alter_topic_topic_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Toggle to show/hide subject on the website'),
        ),
    ]
