# Generated by Django 4.2.14 on 2026-04-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculum", "0014_add_coupon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="per_user_limit",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="How many times a single user can use this coupon",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="usage_limit",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Total times this coupon can be used globally",
                null=True,
            ),
        ),
    ]
