# Generated by Django 4.2.14 on 2026-05-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculum", "0016_coupon_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="topic_type",
            field=models.CharField(
                choices=[
                    ("text", "Text Article"),
                    ("video", "Video Lesson"),
                    ("quiz", "Quiz"),
                    ("exam", "Mock Exam"),
                    ("essay", "Essay"),
                ],
                default="text",
                max_length=10,
            ),
        ),
    ]
