# Generated by Django 4.2.14 on 2026-05-14 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("essays", "0003_essaytopic_semantic_keywords"),
        ("curriculum", "0017_alter_topic_topic_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="essay_topic",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the essay to use for this topic (only for Essay topic type)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="essays.essaytopic",
            ),
        ),
    ]
