# Generated by Django 4.2.14 on 2026-05-14 04:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EssayTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=200, unique=True)),
                ("description", models.TextField()),
                ("instructions", models.TextField()),
                (
                    "difficulty_level",
                    models.IntegerField(
                        choices=[(1, "Beginner"), (2, "Intermediate"), (3, "Advanced")]
                    ),
                ),
                ("min_words", models.PositiveIntegerField(default=250)),
                ("max_words", models.PositiveIntegerField(default=1000)),
                ("time_limit_minutes", models.PositiveIntegerField(default=30)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_essay_topics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Essay Topic",
                "verbose_name_plural": "Essay Topics",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EssayAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attempt_number", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("IN_PROGRESS", "In Progress"),
                            ("SUBMITTED", "Submitted"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("GRADED", "Graded"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(blank=True)),
                ("word_count", models.PositiveIntegerField(default=0)),
                ("character_count", models.PositiveIntegerField(default=0)),
                ("paragraph_count", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("graded_at", models.DateTimeField(blank=True, null=True)),
                ("time_limit_seconds", models.PositiveIntegerField()),
                ("is_timed", models.BooleanField(default=True)),
                ("timer_expired", models.BooleanField(default=False)),
                ("final_score", models.FloatField(blank=True, null=True)),
                ("grammar_score", models.FloatField(blank=True, null=True)),
                ("spelling_score", models.FloatField(blank=True, null=True)),
                ("punctuation_score", models.FloatField(blank=True, null=True)),
                ("readability_score", models.FloatField(blank=True, null=True)),
                ("vocabulary_score", models.FloatField(blank=True, null=True)),
                ("structure_score", models.FloatField(blank=True, null=True)),
                ("relevance_score", models.FloatField(blank=True, null=True)),
                (
                    "grading_status",
                    models.CharField(db_index=True, default="pending", max_length=20),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "essay_topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="essays.essaytopic",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="essay_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="essays_essa_user_id_c689d8_idx"
                    ),
                    models.Index(
                        fields=["essay_topic", "status"],
                        name="essays_essa_essay_t_2aed1d_idx",
                    ),
                    models.Index(
                        fields=["grading_status", "status"],
                        name="essays_essa_grading_f7e159_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="essays_essa_created_0af86c_idx"
                    ),
                ],
                "unique_together": {("user", "essay_topic", "attempt_number")},
            },
        ),
    ]
