# Generated by Django 4.2.14 on 2026-05-14 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("essays", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EssayDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("word_count", models.PositiveIntegerField(default=0)),
                ("saved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "essay_attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drafts",
                        to="essays.essayattempt",
                    ),
                ),
            ],
            options={
                "ordering": ["-saved_at"],
                "indexes": [
                    models.Index(
                        fields=["essay_attempt", "saved_at"],
                        name="essays_essa_essay_a_a5e691_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EssayAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("typing_events", models.PositiveIntegerField(default=0)),
                ("paste_events", models.PositiveIntegerField(default=0)),
                ("copy_events", models.PositiveIntegerField(default=0)),
                ("delete_events", models.PositiveIntegerField(default=0)),
                ("focus_loss_count", models.PositiveIntegerField(default=0)),
                ("inactivity_seconds", models.PositiveIntegerField(default=0)),
                ("longest_pause_seconds", models.PositiveIntegerField(default=0)),
                (
                    "suspicious_activity",
                    models.BooleanField(db_index=True, default=False),
                ),
                ("risk_score", models.FloatField(default=0)),
                ("last_activity_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "essay_attempt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="essays.essayattempt",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["suspicious_activity"],
                        name="essays_essa_suspici_c83a56_idx",
                    ),
                    models.Index(
                        fields=["risk_score"], name="essays_essa_risk_sc_698708_idx"
                    ),
                ],
            },
        ),
    ]
