# Generated by Django 4.2.14 on 2026-05-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("essays", "0002_essaydraft_essayanalytics"),
    ]

    operations = [
        migrations.AddField(
            model_name="essaytopic",
            name="semantic_keywords",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
