# Generated by Django 4.2.14 on 2026-05-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0003_essaytopic_semantic_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='essayattempt',
            name='ai_report',
            field=models.TextField(blank=True, help_text='Saved AI-generated report for this attempt.', null=True),
        ),
    ]
